# Configuración de la Base de Datos (PostgreSQL en Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/cuentasbd
spring.datasource.username=postgres
spring.datasource.password=supersecret
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Spring Data JPA / Hibernate
# 'update' creará o actualizará las tablas automáticamente basándose en tus clases @Entity
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola las consultas SQL que Spring ejecuta por detrás (útil para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true